### PR TITLE
Sdxl

### PR DESCRIPTION
**Pull request by Necr0x0Der**

### CODE REVIEW

**Comment by noskill** [comment]
model type can be read from model_index.json. Field is called "_class_name".

**Comment by noskill** [comment]
Passing model type to Pipe's constructor might be necessary if we loading from a single safetensors file and model is not SDXL or SD1.5 which are detected BasePipe constructor.  But in this case one can simply pass sd_pipe_class which will be used to load the file.

**Comment by Necr0x0Der** [comment]
This PR fixes incorrect operation of the existing code. If you implement correct automatic detection of the model type, this will be good, but it can be done in a separate PR.

**Comment by noskill** [comment]
What is currently working incorrectly? Can you give code that demonstrates incorrect behaviour?

**Comment by noskill** [comment]
Automatic detection from model_config.json is implemented in diffusers https://huggingface.co/docs/diffusers/en/tutorials/autopipeline. Detection from safetensors is implemented in BasePipe's constructor by me, it, indeed might have issues, though i didn't encounter any problems yet.

**Comment by Necr0x0Der** [comment]
If you will try to pass an SDXL model in https://github.com/singnet/metafusion/blob/main/examples/im2im.py , you'll get an incorrect class. Even if you just constructs Prompt2ImPipe, you'll get an incorrect class. Just check what
```
pipe = Im2ImPipe(model_dir+model_id)
type(pipe.pipe)
```
produced for an SDXL model

**Comment by noskill** [comment]
```
from multigen.sessions import GenSession
from multigen.pipes import Im2ImPipe, CIm2ImPipe, get_diffusion_scheduler_names


model_dir = "./models-sd/"
#model_id = "icbinp"
model_id = 'SDXL/juggernautXL_v8Rundiffusion'

pipe = Im2ImPipe(model_dir + model_id)
print(pipe.model_id)
print(type(pipe.pipe))                  
```

this script prints 
./models-sd/SDXL/juggernautXL_v8Rundiffusion
<class 'diffusers.pipelines.stable_diffusion_xl.pipeline_stable_diffusion_xl_img2img.StableDiffusionXLImg2ImgPipeline'>

**Pull request merged**
